---
kind: pipeline
type: docker
name: Build

steps:
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      insecure: false
      repo: registry.silvain.eu:5000/silvain.eu/monsieurpatateplanning
      registry: registry.silvain.eu:5000
      tags:
        - latest
